name: DoomFire
version: @version@
main: me.giverplay.doomfire.DoomFire
api-version: 1.16
authors: [ GiverPlay, Akira ]
description: Implement Doom Fire algorithm in Bukkit and Spigot API
website: https://github.com/foca-enterprises
commands:
  doomfire:
    description: Comando principal
    aliases: [ fire ]